### ISSUE TITLE
Declare include nft data set in the latest version

### ISSUE THREAD

**Issue by CarlosAmaral** [norips/Projet_MBA#2]
Hey @norips 

Thanks for the great work. In your latest changes you aren't declaring the markers from a Data folder as in `Canvas t = new Canvas("Pinball","Data/pinball");`. Are you receiving them via http? 

Thanks.

**Comment by norips** [comment]
Hi, yes they are downloaded from [here](https://github.com/norips/Projet_MBA/blob/master/ARMuseumProj/ARMuseum/src/main/java/fr/norips/ar/ARMuseum/Presentation.java#L74). It download a JSON config file and download all the asset including the nft marker (fset,fset3 and iset files). I added the format.json file to the root of the project so you can take a look into. You can try the app also by setting this domain :`norips.me` instead of `norips.ddns.net` in the file quoted earlier.

**Comment by CarlosAmaral** [comment]
Thank you. Now the building is blowing up: `Failed to ensure directory: /storage/external_SD/Android/data/fr.norips.ARMuseum/files
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Android/data/fr.norips.ARMuseum/files/format.json: open failed: ENOENT (No such file or directory)`

and 

`W/System.err: java.net.UnknownHostException: Unable to resolve host "norips.ddns.net": No address associated with hostname`

**Comment by norips** [comment]
I made a commit pull, and retry. It must be working now :smile:

**Comment by CarlosAmaral** [comment]
It works. Thanks!

**Comment by CarlosAmaral** [comment]
PS: Can I load the markers through the Marker folder? instead of those urls?
