### ISSUE TITLE
Re: Declare include nft data set in the latest version

### ISSUE THREAD

**Issue by CarlosAmaral** [norips/Projet_MBA#3]
PS: Can I load the markers through the Marker folder? instead of those urls?

**Comment by norips** [comment]
Yes of course, you can simply add your file to your asset folder and access to it, instead of using the format.json to load the config, you can add them by yourself [here](https://github.com/norips/Projet_MBA/blob/master/ARMuseumProj/ARMuseum/src/main/java/fr/norips/ar/ARMuseum/SimpleRenderer.java#L85) for example, by calling `ConfigHolder.getInstance().load(ArrayList<Canva>)`, this will load your Canva's arraylist to the ConfigHolder instance. 

`ArrayList<Canva> array = new ArrayList<Canva>();`
`Canva  c = new Canvas(name, localFeaturePath);`
`c.addModel(new Model(modelName, pos, pathToTextures, context))`
`array.add(c);`
`...`
`ConfigHolder.getInstance().load(array)`

Something like this should work

**Comment by CarlosAmaral** [comment]
Thank you, again.
